---
- name: Bring in vaulted Ansible Tower secrets
  include_vars: vars/tower-secrets.yml
  when: tower_secrets
  no_log: True

# Temporarily configure tower-cli
# This task could be removed if tower_role module worked in Ansible 2.5 with tower-cli 3.2.1
- name: Configure tower-cli
  template:
    src: 'tower_cli.cfg.j2'
    dest: '~/.tower_cli.cfg'
    mode: '0400'
  changed_when: False

# tower_role module not working properly in Ansible 2.5 with tower-cli 3.2.1
# Someday when the tower_role module actually works:
# # Credential
# - name: Assign RBAC to Team | Credential
#   tower_role:
#     tower_host: "{{ tower_url }}"
#     tower_username: "{{ tower_user }}"
#     tower_password: "{{ tower_pass }}"
#     organization: "{{ tower_org }}"
#     tower_verify_ssl:  "{{ tower_verify_ssl }}"
#     credential: "{{ tower_rbac_credential }}"
#     role: "{{ tower_rbac_role }}"
#     team: "{{ tower_rbac_team }}"
#     state: "present"
#   when: tower_rbac_credential is defined
#
# # Inventory
# - name: Assign RBAC to Team | Inventory
#   tower_role:
#     tower_host: "{{ tower_url }}"
#     tower_username: "{{ tower_user }}"
#     tower_password: "{{ tower_pass }}"
#     organization: "{{ tower_org }}"
#     tower_verify_ssl:  "{{ tower_verify_ssl }}"
#     inventory: "{{ tower_rbac_inventory }}"
#     role: "{{ tower_rbac_role }}"
#     team: "{{ tower_rbac_team }}"
#     state: "present"
#   when: tower_rbac_inventory is defined
#
# # Job Template
# - name: Assign RBAC to Team | Job Template
#   tower_role:
#     tower_host: "{{ tower_url }}"
#     tower_username: "{{ tower_user }}"
#     tower_password: "{{ tower_pass }}"
#     organization: "{{ tower_org }}"
#     tower_verify_ssl:  "{{ tower_verify_ssl }}"
#     job_template: "{{ tower_rbac_job_template }}"
#     role: "{{ tower_rbac_role }}"
#     team: "{{ tower_rbac_team }}"
#     state: "present"
#   when: tower_rbac_job_template is defined
#
# # Workflow
# - name: Assign RBAC to Team | Workflow
#   tower_role:
#     tower_host: "{{ tower_url }}"
#     tower_username: "{{ tower_user }}"
#     tower_password: "{{ tower_pass }}"
#     organization: "{{ tower_org }}"
#     tower_verify_ssl:  "{{ tower_verify_ssl }}"
#     workflow: "{{ tower_rbac_workflow }}"
#     role: "{{ tower_rbac_role }}"
#     team: "{{ tower_rbac_team }}"
#     state: "present"
#   when: tower_rbac_workflow is defined
#
# # Project
# - name: Assign RBAC to Team | Project
#   tower_role:
#     tower_host: "{{ tower_url }}"
#     tower_username: "{{ tower_user }}"
#     tower_password: "{{ tower_pass }}"
#     organization: "{{ tower_org }}"
#     tower_verify_ssl:  "{{ tower_verify_ssl }}"
#     project: "{{ tower_rbac_project }}"
#     role: "{{ tower_rbac_role }}"
#     team: "{{ tower_rbac_team }}"
#     state: "present"
#   when: tower_rbac_project is defined

# Credential
- name: Assign RBAC to Team | Credential
  command: 'tower-cli                                                  \
            role                                                       \
              grant                                                    \
                --team                 "{{ tower_rbac_team }}"         \
                --type                 "{{ tower_rbac_role }}"         \
                --credential           "{{ tower_rbac_credential }}"   \
                {% if not tower_verify_ssl %}
                --insecure
                {% endif %}
         '
  when: tower_rbac_credential is defined

# Inventory
- name: Assign RBAC to Team | Inventory
  command: 'tower-cli                                                  \
            role                                                       \
              grant                                                    \
                --team                 "{{ tower_rbac_team }}"         \
                --type                 "{{ tower_rbac_role }}"         \
                --inventory            "{{ tower_rbac_inventory }}"    \
                {% if not tower_verify_ssl %}
                --insecure
                {% endif %}
         '
  when: tower_rbac_inventory is defined

# Job Template
- name: Assign RBAC to Team | Job Template
  command: 'tower-cli                                                  \
            role                                                       \
              grant                                                    \
                --team                 "{{ tower_rbac_team }}"         \
                --type                 "{{ tower_rbac_role }}"         \
                --job-template         "{{ tower_rbac_job_template }}" \
                {% if not tower_verify_ssl %}
                --insecure
                {% endif %}
         '
  when: tower_rbac_job_template is defined

# Workflow
- name: Assign RBAC to Team | Workflow
  command: 'tower-cli                                                  \
            role                                                       \
              grant                                                    \
                --team                 "{{ tower_rbac_team }}"         \
                --type                 "{{ tower_rbac_role }}"         \
                --workflow             "{{ tower_rbac_workflow }}"     \
                {% if not tower_verify_ssl %}
                --insecure
                {% endif %}
         '
  when: tower_rbac_workflow is defined

# Project
- name: Assign RBAC to Team | Project
  command: 'tower-cli                                                  \
            role                                                       \
              grant                                                    \
                --team                 "{{ tower_rbac_team }}"         \
                --type                 "{{ tower_rbac_role }}"         \
                --project              "{{ tower_rbac_project }}"      \
                {% if not tower_verify_ssl %}
                --insecure
                {% endif %}
         '
  when: tower_rbac_project is defined

# This task could be removed if tower_role module worked in Ansible 2.5 with tower-cli 3.2.1
# Cleanup
- name: Destroy tower_cli config
  file:
    path:  "~/.tower_cli.cfg"
    state: "absent"
  changed_when: False
